/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cels_photofun_MainActivity */

#ifndef _Included_com_cels_photofun_MainActivity
#define _Included_com_cels_photofun_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cels_photofun_MainActivity_PICK_IMAGE
#define com_cels_photofun_MainActivity_PICK_IMAGE 2L
#undef com_cels_photofun_MainActivity_REQUEST_IMAGE_CAPTURE
#define com_cels_photofun_MainActivity_REQUEST_IMAGE_CAPTURE 1L

/*
 * Class:     com_cels_photofun_MainActivity
 * Method:    buildSegmented
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_cels_photofun_MainActivity_buildSegmented
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
